### ISSUE TITLE
Error: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ZiyiiiLiu** [sys-bio/roadrunner#1259]
Hi, I updated my roadrunner to the newest version with 3.12 py, and I can only run one parameter set and got the results, and then meet the error. However, I can run many parameter sets with the previous roadrunner.

How can I fix that?

The error starts at 
```python
def autofunction(r):
    auto = Plugin("tel_auto2000")
    auto.setProperty("SBML", r.getCurrentSBML())
    auto.setProperty("ScanDirection", 'Positive')
    auto.setProperty("PrincipalContinuationParameter", "K_Y") #So the K_Y becomes PAR in the dataset
    auto.setProperty("PreSimulation", "True")
    auto.setProperty("PreSimulationDuration", 30)
    auto.setProperty("RL0", 0.001)
    auto.setProperty("RL1", 10)
    auto.setProperty("NMX", 8000) #8000
    auto.setProperty("NPR", 3) 
    auto.setProperty("KeepTempFiles", True) 
    auto.setProperty("DS", 0.001) #0.001
    auto.setProperty("DSMIN", 0.001) 
    auto.setProperty("DSMAX", 0.01) #0.01
    pts1 = auto.BifurcationPoints
    if 1:
        lbl1     = auto.BifurcationLabels
        biData1  = auto.BifurcationData
```

**Comment by ZiyiiiLiu** [comment]
Even when I changed the parameters in the autofunction(r) and it can't have a simulation result with different parameter sets in ODE, always with An unexpected error occurred: invalid literal for int() with base 10: ''

**Comment by luciansmith** [comment]
I was able to reproduce your problem!  Here's the code I used:

```python
import rrplugins
import tellurium as te

r = te.loads(r"https://www.ebi.ac.uk/biomodels/services/download/get-files/MODEL1708290005/5/BIOMD0000000648_url.xml")
sbmlModel = r.getSBML()

auto = rrplugins.Plugin("tel_auto2000")              
auto.setProperty("SBML", sbmlModel)
auto.execute()

auto2 = rrplugins.Plugin("tel_auto2000")              
auto2.setProperty("SBML", sbmlModel)
auto2.execute()
```

The first time auto.execute runs, it's fine; the second time it crashes.  

@adelhpour : you investigated the memory leak earlier, and my guess is that a fix you made there caused this issue now.  Would you mind looking into it?

**Comment by adelhpour** [comment]
Sure. I'll check it out.

**Comment by ZiyiiiLiu** [comment]
I can install the 3.8.0 roadrunner and run it succssefully with windows version in my own computer, but failed in linux system in school high performance computer. Not sure about the reason, but the linux should be better for running it.

I checked further, and the error is within  auto.execute()---Segmentation fault (core dumped) , and pts1 = auto.BifurcationPoints---An unexpected error occurred: invalid literal for int() with base 10: ''.

**Comment by luciansmith** [comment]
Sorry for the delay, but I finally was able to investigate and fix the issue!  If you need a fix right now, you can find binaries and wheel files at

https://github.com/sys-bio/roadrunner/actions/runs/18299641197

or you can just wait until Roadrunner's next release.  Thank you again for reporting the issue!

**Comment by ZiyiiiLiu** [comment]
Hi Lucian, Thank you so much for the update! Does the upcoming new version solve the memory leaking and also can run successfully?

**Comment by luciansmith** [comment]
I found *a* memory leak that I fixed, so I think that's it, though I hope there aren't others.  (I have tracked memory usage between calls to simulate, and it used to go up, and now stays the same.)  I do know that this segmentation fault issue is definitely fixed.  And yes, the next version will have both fixes.

**Comment by ZiyiiiLiu** [comment]
Hi Lucian,

I still met the segmentation error. I tried to use the patched wheel file sha256:24710521f9d6f3a533569f7f2805d3ddca70e6271bd3f818dc7d9d705285b921 with 3.10 python version linux in the link you provided above.

I did: I created a new env, installed the roadrunner and rrplugin within the whl file, and installed all other packages via pip. 

Then, I tested the patched tool by the code you gave in Feb in this #1259 page. I met the segmentation fault error again.


Could you please let me know if I did something not correct? Thanks!

**Comment by luciansmith** [comment]
Oh, did you update both the rrplugins *and* libroadrunner?  Both will need to be updated to fix the problem.

The latest files are at

https://github.com/sys-bio/roadrunner/actions/runs/19393934808

just in case you're running into a different problem with memory in Python that I also just fixed.

**Comment by ZiyiiiLiu** [comment]
Thanks. Do I use the roadrunner-2.8.0-python-wheels-manylinux_2_28-x86_64 in the link for python linux system? 
There are rrplugin and libroadrunner, and I need to install these two in a new env, and I don't need to install the precious version right?

**Comment by luciansmith** [comment]
Correct!

**Comment by sharkblue2065** [comment]
Hi Lucian, I tried the new version just now, and tied below, but still the same error:

```python
python - << 'EOF'
import rrplugins
import tellurium as te

# Load SBML model directly from URL
r = te.loads(r"https://www.ebi.ac.uk/biomodels/services/download/get-files/MODEL1708290005/5/BIOMD0000000648_url.xml")
sbmlModel = r.getSBML()

print("Model loaded!")

# First AUTO run
auto = rrplugins.Plugin("tel_auto2000")
auto.setProperty("SBML", sbmlModel)
print("Running AUTO (1)...")
auto.execute()
print("AUTO run 1 OK")

# Second AUTO run
auto2 = rrplugins.Plugin("tel_auto2000")
auto2.setProperty("SBML", sbmlModel)
print("Running AUTO (2)...")
auto2.execute()
print("AUTO run 2 OK")

EOF
```

-------output-----------
Model loaded!
Running AUTO (1)...
Segmentation fault (core dumped)

**Comment by sharkblue2065** [comment]
python version is 3.11, and i installed patched rrplugin at first, then the libroadrunner, and then the tellurium via pip.

**Comment by sharkblue2065** [comment]
I tried the 3.12 version, and tried below but also met the same issue:
python - << 'EOF'
import rrplugins
auto = rrplugins.Plugin("tel_auto2000")
print(auto)
EOF


<rrplugins.telplugins.Plugin object at 0x7f584c192300>
Segmentation fault (core dumped)

**Comment by luciansmith** [comment]
Oh, it won't even import!    OK, I'll work on things on this end.  Sorry for the hassle!

**Comment by sharkblue2065** [comment]
Hi Lucian, I guess the problem is execute(). Could you run the code successfully? (to make sure I didnt install process wrong
)

Also, is the problem hard to solve? As I used the roadrunner in my code and paper manuscript, its will be a big problem for me if the code cannot run.

rrplugins imports ✅

tel_auto2000 loads ✅

SBML is valid and parsed by Tellurium ✅

PrincipalContinuationParameter, bounds, and basic AUTO settings are all set ✅

Crash happens inside the native AUTO plugin during execute(), not because of missing config or Python misuse ❌

**Comment by luciansmith** [comment]
I was indeed able to reproduce your problem.  Somehow it now crashes the *first* time execute is run, instead of the second?  Even though I thought I put in this literal test.

I don't think it should be hard to solve--tracking down crashes are a lot more straightforward than tracking down numerical errors.

**Comment by sharkblue2065** [comment]
OK, how long will it be solved?

**Comment by luciansmith** [comment]
OK, I don't know if this will work for you or not, but I had your issue with the manylinux wheel files using WSL in Windows (the ubuntu-like thing that Windows now can run), and these wheel files actually ran the test program.  Valgrind still flags it as having errors on exiting, but at least for me, that didn't prevent the file from running.  If you'd like to test it out, grab the wheel files from:

https://github.com/sys-bio/roadrunner/actions/runs/19721008712

**Comment by sharkblue2065** [comment]
Thank you for your reply. But I need to run the project in HPC - linux system as I have more than 50,000 parameter sets, so it cannot work right?

**Comment by luciansmith** [comment]
The manylinux wheels should work on any linux system including HPC.  They didn't, and they also didn't work on WSL.  I fixed something (a new/delete mismatch) that made it work on WSL, so my hope is that this means they'll work on HPC, too.

**Comment by sharkblue2065** [comment]
Hi Lucian, thanks. I tried the new roadrunner and rrplugin files, here is what I did: 1. create a new env to install roadrunner+rrplugin+tellurium, here the first 2 are from the whl files of the link. 2. I run the code below, and got the result:
CommandLine Error: Option 'x86-experimental-lvi-inline-asm-hardening' registered more than once! LLVM ERROR: inconsistency in registered CommandLine options Aborted (core dumped).

Anywhere I did not correct?

```python
python - << 'EOF'
import rrplugins
import tellurium as te

print("Loading SBML from local file (model.xml)...")
r = te.loadSBMLModel("model.xml")
sbmlModel = r.getSBML()
print("SBML loaded, length:", len(sbmlModel))

auto = rrplugins.Plugin("tel_auto2000")              
auto.setProperty("SBML", sbmlModel)
print("Running first AUTO2000...")
auto.execute()

auto2 = rrplugins.Plugin("tel_auto2000")              
auto2.setProperty("SBML", sbmlModel)
print("Running second AUTO2000...")
auto2.execute()
EOF
```

**Comment by sharkblue2065** [comment]
Hi Lucian, I tried the new link again, still shows the auto-2000 crash inside. what I did is 1. create a new env-3.11 python
, 2. install tellurium, 3. install rrplugin and roadrunner to rewrite the versions installed with tellurium. 4. run the code below, 5 results is 'RR ok AUTO plugin object: 37792048 Segmentation fault (core dumped)'. 

✅ rrplugins works.

✅ The Hello plugin executes fine → core plugin system is OK.

❌ Only Auto-2000 segfaults on executePlugin → crash is inside that plugin.

Please let me know whether the install order is correct. Thanks.

```python
python - << 'EOF'
import antimony, roadrunner, rrplugins

ant = """
model test
  J1: S1 -> S2; k*S1
  S1 = 1; S2 = 0; k = 0.5;
end
"""

# Antimony -> SBML
antimony.loadAntimonyString(ant)
mname = antimony.getMainModuleName()
sbml = antimony.getSBMLString(mname)

# RoadRunner from SBML
rr = roadrunner.RoadRunner(sbml)
print("RR ok")

# AUTO via rrplugins (note the name Auto-2000)
pm = rrplugins.createPluginManager()
rrplugins.loadPlugins(pm)
auto = rrplugins.getPlugin(pm, "Auto-2000")
print("AUTO plugin object:", auto)

rrplugins.setPluginProperty(auto, "SBML", sbml)
rrplugins.executePlugin(auto)

print("AUTO run finished")
EOF
```

**Comment by sharkblue2065** [comment]
Hi, I tried another linux server to install the patched files in https://github.com/sys-bio/roadrunner/actions/runs/19721008712, to test whether the auto-2000 work. But it still doesn't work.

I copied the analysis of GPT (not sure whether it's analysis is correct) here:
Summary

The AUTO-2000 plugin fails to run in the patched RoadRunner 2.8 environment because the installed rrplugins wheel and the included libtel_auto2000.so library do not share a compatible plugin ABI with the Python wrapper (telplugins_c_api.so).
This ABI mismatch leads to:

Bad Handle errors when calling setPluginProperty()

Inability to instantiate the plugin via Plugin("Auto-2000")

In some environments, segmentation faults when the Python C-API attempts to dereference mismatched function tables or plugin structures.

Although getPluginNames() lists "Auto-2000" and getPlugin() returns a nonzero handle, the returned handle points to a plugin struct whose layout does not match what the Python wrapper expects. Therefore, any call that writes or reads plugin parameters results in undefined behavior.

**Comment by sharkblue2065** [comment]
An update after trying 2.6, 2.7 and 2.8-many patched whl versions and 2.4, fortunately I found the 2.40 can run the auto2000 well with rrplugin=2.0.4, i will use the 2.4 now though it has a memory leaking ;-). I test these versions using below code, and if the code can run well then the auto is good:

(My naive guess about the core dumped error: the updated rrplugins can't use the auto 2000 due to the above reasons, and the memory leaking exists from the original rrplugin 2.0.4. However, the newest **3.8.0-win** can run auto successfully, but i need to run the code in linux hpc due to huge amount of par sets )

```python
python - << 'EOF'
import rrplugins
import tellurium as te

r = te.loads(r"https://www.ebi.ac.uk/biomodels/services/download/get-files/MODEL1708290005/5/BIOMD0000000648_url.xml")
sbmlModel = r.getSBML()

auto = rrplugins.Plugin("tel_auto2000")              
auto.setProperty("SBML", sbmlModel)
auto.execute()

auto2 = rrplugins.Plugin("tel_auto2000")              
auto2.setProperty("SBML", sbmlModel)
auto2.execute()
EOF
```

**Comment by luciansmith** [comment]
Well, I'm glad you found something that works for you for now, and I will continue to try to track down the error so you can use everything more straightforwardly!  I appreciate your willingness to test a variety of things, and I will probably have more candidates for testing soon.  And knowing that a previous version worked is also helpful for me for tracking down the error, so I appreciate that, as well.

I wasn't sure if in the end you were getting the LLVM error (which seems to stem from multiple LLVM versions) or the segfault error.  Or both!  Either way, I'm going to try to see if I can track down a test environment that duplicates the errors you're finding.  Thank you again!

**Comment by sharkblue2065** [comment]
Hi Lucian, Thank you for your reply! Yes, the roadrunner 2.40+rrplugin 2.0.4+tellurium 2.2.8 can work together good and run the auto2000 successfully (with memory leaking in rrplugin). The rrplugin 2.6, 2.7, 2.8 all has the core dumped error, but I didn't try the previous rrplugin versions. 

For memory leaking: it may exist in all versions of rrplugin.
For core dumped error: it should exist in the rrplugin versions after 2.0.4.

For the LLVM error, I never met this one after changing the hpc server, so i dont think its a problem now.

**Comment by sharkblue2065** [comment]
Also, some parameters are with the error , some not:
Traceback (most recent call last):
  File "/work/dal075239/SCLC/SCLC_code_updated3_frame/subnet_generate.py", line 581, in <module>
    simulate(model)
RuntimeError: Object of type <class 'NamedArray'> appears to be C subclassed NumPy array, void scalar, or allocated in a non-standard way.NumPy reserves the right to change the size of these structures. Projects are required to take this into account by either recompiling against a specific NumPy version or padding the struct and enforcing a maximum NumPy version.
Exception ignored in: 'PyDataMem_UserFREE'
Traceback (most recent call last):
  File "/work/dal075239/SCLC/SCLC_code_updated3_frame/subnet_generate.py", line 581, in <module>
    simulate(model)
ValueError: PyCapsule_GetPointer called with invalid PyCapsule object

**Comment by luciansmith** [comment]
I can report that I was able to reproduce memory errors in ubuntu, and that they show up using valgrind.  Unfortunately, while that setup enabled me to find a variety of memory errors, there were still more that I have not yet been able to track down.

However, that's not the error you're getting!  The NumPy message means that this particular problem is caused by having a version on NumPy installed that is different from the version we used when we built roadrunner.  I have not always been great about ensuring that a particular version of numpy was asked for in the requirements.txt file; if you tell me which version of roadrunner you're using, I hopefully should be able to tell you which version of numpy that means you should use.

**Comment by sharkblue2065** [comment]
Thank you for the quick reply Lucian! I use the libroadrunner 2.40+rrplugin 2.0.4+tellurium 2.2.8 with python 3.10.

**Comment by luciansmith** [comment]
OK, I believe that means you should use numpy 1.25.2!

**Comment by sharkblue2065** [comment]
Finally solved the numpy error, it should work with libroadrunner 2.5.0.
The previous error is because when installing libroadrunner, it will install the numpy>=1.26 automatically.
